name: automatic testing

on: [push]
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - name : checkout repository code
      uses : actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name : install repository
      run : |
        npm i;
        node tests "ts-node App/src/main.ts"